### ISSUE TITLE
Update cho new version của HASS bạn ơi

### ISSUE THREAD

**Issue by ntsonyx75f** [olli-ai/maika_assistant#10]
![image](https://user-images.githubusercontent.com/114508107/194702367-6b82660d-3282-46c7-9d01-02fbdb2f8090.png)

![image](https://user-images.githubusercontent.com/114508107/194702433-dbf161c3-9a61-4d1a-8c73-f846ee84014f.png)

**Comment by lyntcelec** [comment]
Done nhé

**Comment by linguyen1511** [comment]
done nhé
