### ISSUE TITLE
Lỗi báo code:1007 không tích hợp được Maika với Home Assitant

### ISSUE THREAD

**Issue by Trinhgvt** [olli-ai/maika_assistant#12]
Hiện tại mình đang bị lỗi mã code 1007 trên app Maika
![image](https://user-images.githubusercontent.com/105347860/198521509-bfb86d7b-2232-428e-a22a-beea5ccc8fb2.png)

Xin hỗ trợ mình với. cảm ơn

**Comment by linguyen1511** [comment]
Bạn report detail hơn giúp mình, bạn dùng version Hass nào Maika component nào, bạn chép config của bạn lên đây cho mình xem thử. Nếu có thể bạn show thêm log lỗi của Maika component trong Hass để mình xem.

**Comment by t2quan90** [comment]
mình bị lỗi như trên. đã làm theo đúng như hướng dẫn mà ko được .tại app đã copy key ấn tiếp thì hoenej mã lỗi như ảnh trên

**Comment by linguyen1511** [comment]
Bạn report detail hơn giúp mình bạn dùng version nào, cả Hass và Maika, ngoài ra bạn chép config lên đây luôn mình mới xem bạn đã sai chỗ nào, bạn show log Maika component lúc nó chạy thì log báo lỗi như thế nào
