### ISSUE TITLE
{"status":1,"msg":"Hass client is not connected","code":1007}

### ISSUE THREAD

**Issue by Khoagip** [olli-ai/maika_assistant#13]
Hix, ai fix giùm với

"home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "aarch64",
    "timezone": "UTC",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.0",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "maika_assistant": {
      "version": "2022.10.1",
      "requirements": [
        "websockets",
        "aiohttp"

**Comment by LeNgoc311** [comment]
Bạn gửi file config, phần config maika_assistant tại đây giúp mình nhé

**Comment by Khoagip** [comment]
Mình đã làm được rồi, lỗi do lúc restart lại home assistant nó load chưa
xong mình đã nhấn next trong app maika

Vào Th 3, 1 thg 11, 2022 lúc 09:52 LeNgoc311 ***@***.***> đã
viết:

**Comment by LeNgoc311** [comment]
Ok bạn nhé
