### ISSUE TITLE
Integration error: maika_assistant - Integration 'maika_assistant' not found.

### ISSUE THREAD

**Issue by tuank45** [olli-ai/maika_assistant#14]
-HASS báo lỗi như thế này và không cho khởi động lại
Integration error: maika_assistant - Integration 'maika_assistant' not found.
-đường dẫn trong pi: /config/custom_components/maika_assistant
-trong YAML :
  maika_assistant:
  project_id: "MAIKA"
  url: 192.168.1.200:8123  
api_key:2ffc099d99a6413211704d8032c1d9867b974ed02f6b206ff333adebb9480072d18a16428869eeae9e4df5d9d281dbc0
  report_state: true
bác nào chỉ giùm với.tks!

**Comment by linguyen1511** [comment]
Bạn tắt config maika_assistant trong configuration.yaml trước rồi restart Hass, vì Hass của bạn phải đc restart thì nó mới load maika_assistant component. Xong thì mới bắt đầu mở config

**Comment by tuank45** [comment]
Cảm ơn bạn, mình đã thêm được Hass vào rồi
Tuy nhiên minhg có thắc mắc là mỗi khi có thêm thiết bị mới liên kết vào HASS,, mà muốn thêm vào Maika thì lại phải làm lại từ bước lấy key ak?

**Comment by LeNgoc311** [comment]
Không cần nha bạn, 
Bạn chỉ mở app Maika là app load và tự động sync thiết bị mới nhất qua thôi.
