### ISSUE TITLE
Maika nhận hass nhưng sao không có dịch vụ để gọi TTS cho Maika? Như kiểu gọi loa Google home mini theo ngữ cảnh? xin giúp đỡ

### ISSUE THREAD

**Issue by nnhd2212** [olli-ai/maika_assistant#15]
![image](https://user-images.githubusercontent.com/71199163/219907523-5a7d361c-50cc-499d-bee5-2d21ee26a9ec.png)
![image](https://user-images.githubusercontent.com/71199163/219907536-b03fa09f-5b53-4150-86c5-4caf090e1b69.png)
![image](https://user-images.githubusercontent.com/71199163/219907546-8b570010-f6aa-468b-8523-3fc9cef4299f.png)

**Comment by linguyen1511** [comment]
vì Maika component không có support tính năng này nhé bạn

**Comment by nnhd2212** [comment]
> do linh kiện Maika không hỗ trợ tính năng này bạn nhé

Trong tương lai có bổ sung không bạn, việc sử dụng được TTS chủ động kết hợp với các cảm biến rất là hay và được sử dụng nhiều, đây là một thứ rất cần phát triển, xin góp ý thêm.
