### ISSUE TITLE
Liên kết với hass thất bại

### ISSUE THREAD

**Issue by nvTrung412** [olli-ai/maika_assistant#6]
Sáng hôm qua 8/8 kết nối Maika và Home Assistant (thông qua dịch vụ smarthome của Javis smart) vẫn bình thường.
Tuy nhiên đến chiều Maika mất kết nối với Hass.
Sáng nay cài lại, các bước ok cho đến bước cuối cùng thì Maika thông báo kết nối thất bại

**Comment by linguyen1511** [comment]
Lỗi phía server, đã fix xong, bạn check lại nhé
