### ISSUE TITLE
Component error: cannot import name 'button' from 'homeassistant.components'

### ISSUE THREAD

**Issue by dohuuben** [olli-ai/maika_assistant#7]
Lỗi khi cấu hình maika

![image](https://user-images.githubusercontent.com/61677991/185805231-4d71ea13-499e-408f-a1fa-c8afa30883c0.png)

**Comment by lyntcelec** [comment]
Bạn giúp mình check version Hass của bạn và version maika component bạn đang dùng nhé, rồi báo lên đây để mình biết thêm thông tin

**Comment by dohuuben** [comment]
Version maika: 2022.8.0
Varsion hass: 2022.08.5
![image](https://user-images.githubusercontent.com/61677991/187844539-9e1cbb5e-600f-490d-b6d4-8a9471aade9e.png)

**Comment by lyntcelec** [comment]
bạn thử với version mới nhất 2022.9.7 mình mới update
