### ISSUE TITLE
Không link được Home assistant với app của MAIKA

### ISSUE THREAD

**Issue by ntsonyx75f** [olli-ai/maika_assistant#8]
Mình đã thực hiện như hướng dẫn nhưng báo lỗi.
HASS version:
![image](https://user-images.githubusercontent.com/114508107/192694810-aa3b3c29-9cc8-4431-bdfc-e92f2e3fc61f.png)
![image](https://user-images.githubusercontent.com/114508107/192695836-664f08f6-f251-4a74-a340-80bde972a132.png)

Error:
![image](https://user-images.githubusercontent.com/114508107/192695519-afdc3368-feaa-460e-97bc-74717e511b3d.png)

**Comment by lyntcelec** [comment]
bạn thử với version mới nhất 2022.9.7 mình mới update

**Comment by ntsonyx75f** [comment]
connect được rồi bạn. Cám ơn nhiều.
Nhưng cái này mỗi lần update new version cho HASS thì phải connect lại hay sao bạn
