### ISSUE TITLE
Key trên app maika hay bị đổi khi setup.

### ISSUE THREAD

**Issue by Huy0905** [olli-ai/maika_assistant#9]
Phần Key trên app Maika khi liên kết phải copy để dán lên Ha. 
![image](https://user-images.githubusercontent.com/75462313/193174782-323d2cd4-94d2-4111-921f-c51bece6cb45.png)
- Với những điện thoại đa nhiệm không tốt. Sau khi copy Key thì phải thu nhỏ ứng dụng và dán vào code Ha.
 Sau khi dán vào Ha và khởi động lại Ha xong, quay lại ứng dụng Maika để thao tác thì app Maika rất hay bị load lại > Key bị đổi > phải thao tác lại việc lấy Key và liên kết với Ha từ đầu do lúc này Key đã bị đổi. Khiến cho việc liên kết Maika đến HA nhiều khi rất mất thời gian.
- Mong muốn với 1 tài khoản chỉ nên có 1 Key cho ae dễ thao tác. Hoặc có thêm nút đổi key để người dùng  có thể chủ động việc đổi key nếu lo ngại vấn để bảo mật, thay bị key tự thay đổi như bậy giờ.

**Comment by linguyen1511** [comment]
Key này phải thay đổi chứ không thể dùng 1 key để bảo mật bạn ơi, bạn có thể chép vào Zalo, rồi quay lại app Maika ngay lập tức rồi mở app Zalo trên PC để chép key đó ra. Sẽ ko bị tình trạng lúc quay lại app bị load lại đâu bạn, mình vẫn dùng cách này suốt
